
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 24 14:12:25 AEST 2015
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface CUPToken {
  /* terminals */
  public static final int DIVIDE = 10;
  public static final int LBRACKET = 19;
  public static final int KW_PROCEDURE = 28;
  public static final int EQUALS = 11;
  public static final int KW_DO = 24;
  public static final int LPAREN = 2;
  public static final int GREATER = 16;
  public static final int KW_CONST = 23;
  public static final int LESS = 15;
  public static final int MINUS = 8;
  public static final int RPAREN = 3;
  public static final int SEMICOLON = 4;
  public static final int GEQUALS = 14;
  public static final int RANGE = 17;
  public static final int LEQUALS = 13;
  public static final int NEQUALS = 12;
  public static final int COMMA = 18;
  public static final int KW_WRITE = 35;
  public static final int PLUS = 7;
  public static final int ASSIGN = 6;
  public static final int KW_TYPE = 32;
  public static final int KW_CALL = 22;
  public static final int EOF = 0;
  public static final int RBRACKET = 20;
  public static final int KW_BEGIN = 21;
  public static final int error = 1;
  public static final int NUMBER = 38;
  public static final int KW_IF = 27;
  public static final int TIMES = 9;
  public static final int COLON = 5;
  public static final int ILLEGAL = 36;
  public static final int KW_END = 26;
  public static final int KW_ELSE = 25;
  public static final int KW_READ = 29;
  public static final int KW_VAR = 33;
  public static final int KW_WHILE = 34;
  public static final int KW_THEN = 31;
  public static final int KW_RESULT = 30;
  public static final int IDENTIFIER = 37;
}

